const express = require('express');
const path = require('path');

const app = express();
const port = process.env.PORT || 3000;

const imagePaths = [
  'https://w0.peakpx.com/wallpaper/625/394/HD-wallpaper-attitude-anime-mask-boy-anime.jpg',
  'https://w0.peakpx.com/wallpaper/539/90/HD-wallpaper-thomas-shelby-anime-attitude-sad-tv-series.jpg',
  'https://w0.peakpx.com/wallpaper/594/379/HD-wallpaper-best-attitude-anime-boy-best-attitude-attitude-anime-boy-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/166/571/HD-wallpaper-animation-anime-attitude-cool.jpg',
  'https://w0.peakpx.com/wallpaper/527/948/HD-wallpaper-bad-boy-anime-red-eye-animation-attitude-look.jpg',
  'https://w0.peakpx.com/wallpaper/701/873/HD-wallpaper-attitude-joker-3d-animation-colourful-attitude-joker-animation-christopher-nolan-colourful.jpg',
  'https://w0.peakpx.com/wallpaper/569/514/HD-wallpaper-bad-boy-anime-pink-hair-animation-attitude-look.jpg',
  'https://w0.peakpx.com/wallpaper/644/227/HD-wallpaper-black-attitude-anime-face-black-background.jpg',
  'https://w0.peakpx.com/wallpaper/624/766/HD-wallpaper-attitude-anime-anime-keren-boy.jpg',
  'https://w0.peakpx.com/wallpaper/20/158/HD-wallpaper-bad-boy-anime-attitude-look-animation.jpg',
  'https://w0.peakpx.com/wallpaper/475/428/HD-wallpaper-bad-boy-anime-college-boy-animation-attitude-look.jpg',
  'https://w0.peakpx.com/wallpaper/755/183/HD-wallpaper-bad-boy-anime-anime-boy-smoking-animation-attitude-look.jpg',
  'https://w0.peakpx.com/wallpaper/791/27/HD-wallpaper-cute-boy-kpop-korean-lovely-handsome-anime-cutness-attitude-whitr.jpg',
  'https://w0.peakpx.com/wallpaper/900/705/HD-wallpaper-attitude-anime-goku-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/868/137/HD-wallpaper-best-anime-boy-anime-attitude-boy-cool-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/690/711/HD-wallpaper-attitude-anime-anime-kun-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/791/822/HD-wallpaper-attitude-anime-yakumo-anime-yakumo-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/221/108/HD-wallpaper-bad-boy-anime-painting-art-art-work-attitude-look.jpg',
  'https://w0.peakpx.com/wallpaper/955/269/HD-wallpaper-black-attitude-animated-black-background-pink-hoodie.jpg',
  'https://w0.peakpx.com/wallpaper/672/946/HD-wallpaper-attitude-anime-misaka-mikoto-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/112/356/HD-wallpaper-attack-on-titan-levi-a-attack-on-titan-anime-attitude-anime-yellow-levi-ackerman-manga.jpg',
  'https://w0.peakpx.com/wallpaper/496/474/HD-wallpaper-madara-uchiha-anime-attitude-badass-madara-madarauchiha-naruto-naruto-shippuuden-otaku-shinobi-uchiha.jpg',
  'https://w0.peakpx.com/wallpaper/728/784/HD-wallpaper-attitude-anime-black-boy-black-boy-anime.jpg',
  'https://w0.peakpx.com/wallpaper/386/918/HD-wallpaper-happy-day-action-love-animals-attitude-bards-dark-love-people-sad.jpg',
  'https://w0.peakpx.com/wallpaper/483/292/HD-wallpaper-attitude-anime-smoking-boy-smoking-boy-anime.jpg',
  'https://w0.peakpx.com/wallpaper/393/606/HD-wallpaper-attitude-anime-anime-marah-girl.jpg',
  'https://w0.peakpx.com/wallpaper/503/863/HD-wallpaper-attitude-anime-bird-boy-bird-boy.jpg',
  'https://w0.peakpx.com/wallpaper/573/824/HD-wallpaper-attitude-anime-orek-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/343/583/HD-wallpaper-attitude-anime-red-hair-anime.jpg',
  'https://w0.peakpx.com/wallpaper/645/828/HD-wallpaper-attitude-anime-attitude-boy-attitude-boy.jpg',
  'https://w0.peakpx.com/wallpaper/8/212/HD-wallpaper-attitude-anime-smart-boy-smart-boy-anime.jpg',
  'https://w0.peakpx.com/wallpaper/650/581/HD-wallpaper-attitude-anime-danger-boy-danger-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/478/155/HD-wallpaper-bad-boy-anime-fighting-with-sword-bad-boy-anime-anime-boy-fighting-with-sword-animation-attitude-look.jpg',
  'https://w0.peakpx.com/wallpaper/915/898/HD-wallpaper-attitude-anime-anime-starry-sky-boy.jpg',
  'https://w0.peakpx.com/wallpaper/600/322/HD-wallpaper-anime-boy-anime-boy-anime-boys-cute-cute-anime-boy-cute-anime-boys-lonely-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/356/422/HD-wallpaper-anime-boy-aesthetic-anime-anime-boy-anime-boys-lonely-sad-anime-boy-sad-anime-boys-window.jpg',
  'https://w0.peakpx.com/wallpaper/418/600/HD-wallpaper-anime-boy-aesthetic-anime-boys-creepy-creepy-anime-boy-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/560/1001/HD-wallpaper-anime-boy-anime-anime-boy-anime-boys-demon-depressed-lonely-sad-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/934/24/HD-wallpaper-sad-anime-boy-aesthetic-anime-boy-anime-boys-depressed-lonely-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/362/897/HD-wallpaper-anime-boy-aesthetic-aesthetic-anime-aesthetic-anime-boy-anime-aesthetic-anime-boy-cute-cute-anime-boy-sad-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/144/154/HD-wallpaper-lonely-anime-boy-anime-anime-boy-anime-boys-depressed-lonely-rain-sad-sad-anime-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/773/889/HD-wallpaper-sad-anime-boy-anime-boy-anime-boys-depressed-glitch-lonely-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/356/904/HD-wallpaper-bad-boy-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/738/298/HD-wallpaper-anime-boy-anime-anime-boy-books-library-reading-sun.jpg',
  'https://w0.peakpx.com/wallpaper/151/537/HD-wallpaper-sad-anime-boy-aesthetic-rain-depressed-anime-boys-window-lonely.jpg',
  'https://w0.peakpx.com/wallpaper/133/862/HD-wallpaper-bad-boy-anime-bad-boy.jpg',
  'https://w0.peakpx.com/wallpaper/844/654/HD-wallpaper-anime-anime-boy-umbrella.jpg',
  'https://w0.peakpx.com/wallpaper/721/27/HD-wallpaper-anime-boy-aesthetic-anime-anime-boy-anime-boys-depressed-roses-sad-sad-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/409/219/HD-wallpaper-boys-alone-alone-boy-anime-ash-bad-boy-doraemon-love-pokemon-swahabhaan-trending.jpg',
  'https://w0.peakpx.com/wallpaper/968/860/HD-wallpaper-anime-anime-boys-in.jpg',
  'https://w0.peakpx.com/wallpaper/867/186/HD-wallpaper-anime-boy-aesthetic-anime-boy-aesthetic-boy-black-japanese-writing-sad-anime-boy-sad-boy-shadows.jpg',
  'https://w0.peakpx.com/wallpaper/895/811/HD-wallpaper-anime-boy-aesthetic-aesthetic-anime-boy-anime-boy-anime-boys-cute-cute-anime-boy-cute-anime-boys-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/172/791/HD-wallpaper-anime-boy-anime-boy-cartoon.jpg',
  'https://w0.peakpx.com/wallpaper/760/394/HD-wallpaper-anime-boy-neon-anime-boy-city-color-lonely-lunl-neon-sad.jpg',
  'https://w0.peakpx.com/wallpaper/194/183/HD-wallpaper-anime-boy-anime-boy-anime-boys-depressed-glitch-lonely-sad-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/87/389/HD-wallpaper-anime-boy-aesthetic-aesthetic-anime-boy-anime-anime-boy-anime-boys-cute-cute-anime-boy-cute-anime-boys-pink-sad-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/507/279/HD-wallpaper-animeboy-anime-anime-boy-animes-black-boy-dark-man-sad-sad-boy.jpg',
  'https://w0.peakpx.com/wallpaper/757/1008/HD-wallpaper-anime-sad-sad-boy.jpg',
  'https://w0.peakpx.com/wallpaper/85/561/HD-wallpaper-cute-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/202/483/HD-wallpaper-sad-anime-boy-anime-boy-anime-boys-depressed-lonely-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/899/731/HD-wallpaper-anime-boys-anime-in-naruto-anime.jpg',
  'https://w0.peakpx.com/wallpaper/724/496/HD-wallpaper-aesthetic-anime-boy-anime-boy-anime-boys-depressed-galaxy-lonely-sad-anime-boy-sad-anime-boys-star.jpg',
  'https://w0.peakpx.com/wallpaper/124/434/HD-wallpaper-aesthetic-anime-boy-aesthetic-aesthetic-anime-boy-anime-anime-boy-anime-boys-lonely-anime-boy-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/14/880/HD-wallpaper-anime-anime-boys-glowing.jpg',
  'https://w0.peakpx.com/wallpaper/814/285/HD-wallpaper-best-anime-boy-listening-music-best-anime-boy-anime-boy-listening-music-cute-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/35/35/HD-wallpaper-lonely-boy-sad-boy-anime.jpg',
  'https://w0.peakpx.com/wallpaper/948/960/HD-wallpaper-bad-boy-anime-bad-boy-cool-high.jpg',
  'https://w0.peakpx.com/wallpaper/312/868/HD-wallpaper-anime-boy-demon-red.jpg',
  'https://w0.peakpx.com/wallpaper/497/406/HD-wallpaper-bad-boy-anime-bad-bad-boy-boy.jpg',
  'https://w0.peakpx.com/wallpaper/609/471/HD-wallpaper-hot-anime-boy-anime-boy-cute-hot-anime-cute-anime.jpg',
  'https://w0.peakpx.com/wallpaper/910/272/HD-wallpaper-bad-boy-anime-bad-boy-black-dark.jpg',
  'https://w0.peakpx.com/wallpaper/591/195/HD-wallpaper-masked-anime-boy-anime-mask-ghost-ivan.jpg',
  'https://w0.peakpx.com/wallpaper/847/891/HD-wallpaper-sadness-boy-head-jaw-sad-boy-happy-but-sad-goodhits-new-wallpeper-anime.jpg',
  'https://w0.peakpx.com/wallpaper/112/539/HD-wallpaper-sad-anime-boy-anime-boy-anime-boys-depressed-glitch-lonely-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/977/705/HD-wallpaper-anime-boy-art.jpg',
  'https://w0.peakpx.com/wallpaper/151/306/HD-wallpaper-cute-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/91/83/HD-wallpaper-animeboy-anime-anime-boy-animes-boy-fear-man-sad-sad-boy.jpg',
  'https://w0.peakpx.com/wallpaper/86/27/HD-wallpaper-anime-boy-cool-anime-well-made.jpg',
  'https://w0.peakpx.com/wallpaper/957/636/HD-wallpaper-anime-boy-aesthetic-anime-boy-anime-boys-flower-sad-anime-boy-sad-anime-boys.jpg',
  'https://w0.peakpx.com/wallpaper/972/354/HD-wallpaper-sad-anime-lonelyanime-sad-anime-boy-sad-boy.jpg',
  'https://w0.peakpx.com/wallpaper/92/644/HD-wallpaper-anime-sad-vibes-animated-boy-music-song.jpg',
  'https://w0.peakpx.com/wallpaper/938/871/HD-wallpaper-anime-boys-anime-boy-anime-boys-blue-blue-and-red-boy-red-sword.jpg',
  'https://w0.peakpx.com/wallpaper/337/897/HD-wallpaper-anime-anime-boy-blue-bts-dragon-hot-guy-school-sexy-boy-anime-super.jpg',
  'https://w0.peakpx.com/wallpaper/832/1023/HD-wallpaper-broken-heart-sad-anime-boy-artwork-broken-heart-sad-anime-boy-sad-anime-boy-artwork-broken-heart-boy.jpg',
  'https://w0.peakpx.com/wallpaper/337/897/HD-wallpaper-anime-anime-boy-blue-bts-dragon-hot-guy-school-sexy-boy-anime-super.jpg',
  'https://w0.peakpx.com/wallpaper/430/829/HD-wallpaper-anime-anime-boys-in.jpg',
  'https://w0.peakpx.com/wallpaper/349/544/HD-wallpaper-anime-boy-japan.jpg',
  'https://w0.peakpx.com/wallpaper/239/89/HD-wallpaper-listening-alone-anime-boy-lonely-music.jpg',
  'https://w0.peakpx.com/wallpaper/107/326/HD-wallpaper-sad-anime-boy-anime-anime-boy-boy-dark-anime-boy-sad-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/933/159/HD-wallpaper-sad-emotional-sad-anime-boy-with-crows-background-sad-anime-boy.jpg',
  'https://w0.peakpx.com/wallpaper/766/843/HD-wallpaper-cool-anime-boy-mirror-selfie-animation.jpg',
  'https://w0.peakpx.com/wallpaper/482/977/HD-wallpaper-sad-boy-anime-cry-dead.jpg',
  'https://w0.peakpx.com/wallpaper/803/607/HD-wallpaper-smoking-boy-smoking-anime-smoking-anime.jpg',
  'https://w0.peakpx.com/wallpaper/379/411/HD-wallpaper-smoking-boy-anime-smoking.jpg',
  'https://w0.peakpx.com/wallpaper/179/33/HD-wallpaper-tokyo-revengers-naruto-sky-mikey-smoking-takemichi-draken-anime-rivals.jpg',
  'https://w0.peakpx.com/wallpaper/755/183/HD-wallpaper-bad-boy-anime-anime-boy-smoking-animation-attitude-look.jpg',
  'https://w0.peakpx.com/wallpaper/589/6/HD-wallpaper-levi-ackerman-anime-epic-eren-levi-mikasa-mikasa-ackerman-naruto-orange-smoke.jpg',
  'https://w0.peakpx.com/wallpaper/412/183/HD-wallpaper-naruto-and-kurama-anime-kcm2-orange-smoke-super-uzumaki.jpg',
  'https://w0.peakpx.com/wallpaper/475/428/HD-wallpaper-bad-boy-anime-college-boy-animation-attitude-look.jpg',
  'https://w0.peakpx.com/wallpaper/624/766/HD-wallpaper-attitude-anime-anime-keren-boy.jpg',
];

app.get('/', (req, res) => {
  const randomImagePath = imagePaths[Math.floor(Math.random() * imagePaths.length)];
  res.redirect(randomImagePath);
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
